### PR TITLE
[GH-1126] Fix end game backend bugs

### LINKED ISSUE #1126: [BUG] End game not showing end screen correctly
When playing alone and getting killed by the zone the genserver crashes:
```elixir
[error] GenServer #PID<0.793.0> terminating
** (KeyError) key :id not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
  (dark_worlds_server 0.1.0) lib/dark_worlds_server/engine/engine_runner.ex:317: DarkWorldsServer.Engine.EngineRunner.transform_player_to_myrra_player/1
  (dark_worlds_server 0.1.0) lib/dark_worlds_server/engine/engine_runner.ex:261: DarkWorldsServer.Engine.EngineRunner.broadcast_game_ended/3
  (dark_worlds_server 0.1.0) lib/dark_worlds_server/engine/engine_runner.ex:221: DarkWorldsServer.Engine.EngineRunner.handle_info/2
  (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
  (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
  (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: :check_game_ended
State: %{game_state: %{config: %{game: %{width: 10000, height: 10000, loot_interval_ms: 7000, zone_starting_radius: 14000, zone_modifications: [%{duration_ms: 30000, modification: {:additive, 0}, max_radius: 10000, outside_radius_effects: [%{name: "damage_outside_area", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 999999, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "-10", attribute: "health", modifier: :additive}], projectile_attributes: []}], interval_ms: 500, min_radius: 5000}, %{duration_ms: 20000, modification: {:additive, -45}, max_radius: 10000, outside_radius_effects: [%{name: "damage_outside_area", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 999999, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "-10", attribute: "health", modifier: :additive}], projectile_attributes: []}], interval_ms: 100, min_radius: 5000}, %{duration_ms: 15000, modification: {:additive, -25}, max_radius: 10000, outside_radius_effects: [%{name: "damage_outside_area", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 999999, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "-10", attribute: "health", modifier: :additive}], projectile_attributes: []}], interval_ms: 100, min_radius: 2500}, %{duration_ms: 15000, modification: {:additive, -15}, max_radius: 10000, outside_radius_effects: [%{name: "damage_outside_area", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 999999, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "-10", attribute: "health", modifier: :additive}], projectile_attributes: []}], interval_ms: 100, min_radius: 1000}, %{duration_ms: 120000, modification: {:additive, -5}, max_radius: 10000, outside_radius_effects: [%{name: "damage_outside_area", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 999999, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "-10", attribute: "health", modifier: :additive}], projectile_attributes: []}], interval_ms: 100, min_radius: 0}]}, effects: [%{name: "test_effect", is_reversable: true, effect_time_type: {:duration, %{duration_ms: 6000}}, player_attributes: [%{value: "1.2", attribute: "speed", modifier: :multiplicative}], projectile_attributes: []}, %{name: "heal_30", is_reversable: false, effect_time_type: :instant, player_attributes: [%{value: "30", attribute: "health", modifier: :additive}], projectile_attributes: []}, %{name: "h4ck_dos", is_reversable: true, effect_time_type: {:duration, %{duration_ms: 6000}}, player_attributes: [%{value: "0.7", attribute: "cooldowns", modifier: :multiplicative}], projectile_attributes: [%{value: "1.2", attribute: "speed", modifier: :multiplicative}, %{value: "false", attribute: "remove_on_collision", modifier: :override}]}, %{name: "damage_outside_area", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 999999, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "-10", attribute: "health", modifier: :additive}], projectile_attributes: []}, %{name: "poison", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 5, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "0.95", attribute: "health", modifier: :multiplicative}], projectile_attributes: []}], projectiles: [%{name: "projectile_slingshot", max_distance: 999999, on_hit_effects: [], duration_ms: 999999, base_damage: 8, base_speed: 40, base_size: 20, remove_on_collision: true}, %{name: "projectile_poison_dart", max_distance: 500, on_hit_effects: [%{name: "poison", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 5, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "0.95", attribute: "health", modifier: :multiplicative}], projectile_attributes: []}], duration_ms: 999999, base_damage: 0, base_speed: 60, base_size: 10, remove_on_collision: false}], loots: [%{name: "loot_health", size: 50, effects: [%{name: "heal_30", is_reversable: false, effect_time_type: :instant, player_attributes: [%{value: "30", attribute: "health", modifier: :additive}], projectile_attributes: []}]}], characters: [%{active: true, name: "h4ck", skills: %{"1" => %{name: "slingshot", cooldown_ms: 800, is_passive: false, mechanics: [multi_shoot: %{count: 3, projectile: %{name: "projectile_slingshot", max_distance: 999999, on_hit_effects: [], duration_ms: 999999, base_damage: 8, base_speed: 40, base_size: 20, remove_on_collision: true}, cone_angle: 40}], execution_duration_ms: 250}, "3" => %{name: "poison_dart", cooldown_ms: 800, is_passive: false, mechanics: [simple_shoot: %{projectile: %{name: "projectile_poison_dart", max_distance: 500, on_hit_effects: [%{name: "poison", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 5, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "0.95", attribute: "health", modifier: :multiplicative}], projectile_attributes: []}], duration_ms: 999999, base_damage: 0, base_speed: 60, base_size: 10, remove_on_collision: false}}], execution_duration_ms: 150}}, base_speed: 20, base_size: 80, base_health: 100}, %{active: true, name: "muflus", skills: %{"1" => %{name: "hit", cooldown_ms: 1500, is_passive: false, mechanics: [hit: %{range: 1000, damage: 14, cone_angle: 120, on_hit_effects: []}], execution_duration_ms: 500}, "2" => %{name: "circle_hit", cooldown_ms: 1500, is_passive: false, mechanics: [hit: %{range: 500, damage: 20, cone_angle: 360, on_hit_effects: []}], execution_duration_ms: 800}}, base_speed: 20, base_size: 100, base_health: 100}], skills: [%{name: "slingshot", cooldown_ms: 800, is_passive: false, mechanics: [multi_shoot: %{count: 3, projectile: %{name: "projectile_slingshot", max_distance: 999999, on_hit_effects: [], duration_ms: 999999, base_damage: 8, base_speed: 40, base_size: 20, remove_on_collision: true}, cone_angle: 40}], execution_duration_ms: 250}, %{name: "poison_dart", cooldown_ms: 800, is_passive: false, mechanics: [simple_shoot: %{projectile: %{name: "projectile_poison_dart", max_distance: 500, on_hit_effects: [%{name: "poison", is_reversable: false, effect_time_type: {:periodic, %{interval_ms: 1000, trigger_count: 5, time_since_last_trigger: 0, instant_applicaiton: false}}, player_attributes: [%{value: "0.95", attribute: "health", modifier: :multiplicative}], projectile_attributes: []}], duration_ms: 999999, base_damage: 0, base_speed: 60, base_size: 10, remove_on_collision: false}}], execution_duration_ms: 150}, %{name: "hit", cooldown_ms: 1500, is_passive: false, mechanics: [hit: %{range: 1000, damage: 14, cone_angle: 120, on_hit_effects: []}], execution_duration_ms: 500}, %{name: "circle_hit", cooldown_ms: 1500, is_passive: false, mechanics: [hit: %{range: 500, damage: 20, cone_angle: 360, on_hit_effects: []}], execution_duration_ms: 800}]}, next_id: 6, players: %{1 => %{id: 1, position: %{y: 4796, x: -28 (truncated)
``` 

It also happened when playing with 3 people when one player added.
Update: it also happened in a game of 4 players at the start (2 muflus 2 h4cks).

Less relevant:

Image

- 2 different players. Both finished 1st but one says victory and the other one defeat.

Screenshot 2023-11-13 at 15 52 55

- Error when exiting game:
```elixir
[error] Ranch listener DarkWorldsServerWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.2571.0> exit with reason: {:function_clause, [{DarkWorldsServerWeb.LobbyWebsocket, :terminate, [{:remote, 1000, ""}, %{port: 443, scheme: "http", version: :"HTTP/1.1", path: "/matchmaking/6xqWd7JwBmkBbJbXULKyBK1wVXNtZeffEDFWX4NK", host: "8d57-181-28-89-194.ngrok-free.app", peer: {{127, 0, 0, 1}, 62115}, method: "GET", qs: ""}, %{game_started: true}], [file: ~c"lib/dark_worlds_server_web/websockets/lobby_websocket.ex", line: 54]}, {:cowboy_websocket, :terminate, 3, [file: ~c"/Users/ncontinanza/Projects/Lambdaclass/curse_of_myrra/server/deps/cowboy/src/cowboy_websocket.erl", line: 684]}, {:cowboy_http, :loop, 1, [file: ~c"/Users/ncontinanza/Projects/Lambdaclass/curse_of_myrra/server/deps/cowboy/src/cowboy_http.erl", line: 257]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}
```

### PR DESCRIPTION
**Pull request by Nico-Sanchez**
Closes #1126 

## Motivation

The game should terminate without errors to prevent weird behavior of the game.

## Summary of changes

- [Add terminate/3 clause in LobbyWebsocket to show log info instead of an error](https://github.com/lambdaclass/curse_of_myrra/pull/1137/commits/7106011fc42b7ff8ef134d67c5ffd1be6156110e)
- [Save alive players in every tick and pick one of them as winner when the end game condition is met](https://github.com/lambdaclass/curse_of_myrra/pull/1137/commits/5e292ef3e7ca55980fcfbf0ad469a45cbc1d1baa)
- [Fix winner player final place in game when all players are dead](https://github.com/lambdaclass/curse_of_myrra/pull/1137/commits/3faf2a27c086f6d8af7141cfd9af956d327cf526)

## How has this been tested?

- Tested alone dying by the zone.
- Tested with my phone as a second player:
  - Both dying at the same time by the zone.
  - Killing each player by any means in any order.

## Test additions / changes

No tests.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.

### CODE REVIEW

File: client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs [hunk 1]
```diff
@@ -89,7 +89,17 @@ private int GetRanking()
...
-        return isWinner ? WINNER_POS : Utils.GetAlivePlayers().Count() + 1;
+        // FIXME This is a temporal for the cases where the winner dies simultaneously
+        // FIXME with other/s player/s
+        if (isWinner)
+        {
+            return WINNER_POS;
+        }
+        if (Utils.GetAlivePlayers().Count() == 0)
+        {
+            return 2;
```
Comment (ncontinanza) [inline client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs:100]:
```suggestion
            return SECOND_PLACE_POS;
```

Comment (ncontinanza) [reply client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs:100]: Also, define `private const int SECOND_PLACE_POS = 2;`

**Review by ncontinanza — CHANGES_REQUESTED** [review]

File: client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs (hunk 1 above)
Comment (ncontinanza) [reply client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs:100]: Not a variable but a constant, as we did with `WINNER_POS`, so that we don't have that magic number in the code that may not be obvious if read by someone else without the context of this PR.

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Review by BertovDev — APPROVED** [review]
Cleann!!
