### PR TITLE
Network error modal

### LINKED ISSUE #677: [FEATURE] Errors
## 🚀 Feature

Implement an error dialog so that the client can see when something goes wrong. Some examples:
- Disconnect from game
- Fail to join lobby
- Fail to connect to server 

### Graphic reference
https://drive.google.com/file/d/1ZVE93nwd_-3ti41tXj7enSizKwoW3hFB/view?usp=sharing
image

### PR DESCRIPTION
**Pull request by AminArria**
Closes #677

### CODE REVIEW

File: client/Assets/Scripts/LobbyConnection.cs [hunk 1]
```diff
@@ -207,6 +212,7 @@ public IEnumerator StartGame()
 
     public void Reconnect()
     {
+        Debug.Log("reconect");
```
Comment (ncontinanza) [inline client/Assets/Scripts/LobbyConnection.cs:215]: Should we remove this log? 
In case it's necessary to have it there, it contains a typo ("reconnect")

File: client/Assets/Scripts/SocketConnectionManager.cs [hunk 2]
```diff
@@ -205,6 +206,15 @@ private void OnWebSocketMessage(byte[] data)
         }
     }
 
+    private void onWebsocketClose(WebSocketCloseCode closeCode)
```
Comment (ncontinanza) [inline client/Assets/Scripts/SocketConnectionManager.cs:209]: Following the C# naming convention, this should be `OnWebSocketClose(...)`

File: client/Assets/Scripts/LobbyConnection.cs [hunk 3]
```diff
@@ -412,6 +417,15 @@ private void OnWebSocketMessage(byte[] data)
         }
     }
 
+    private void onWebsocketClose(WebSocketCloseCode closeCode)
```
Comment (ncontinanza) [inline client/Assets/Scripts/LobbyConnection.cs:420]: Following the C# naming convention, this should be OnWebSocketClose(...)

**Review by ncontinanza — DISMISSED** [review]
Nice job! I left a few minor comments about the code.

Also, I noticed that when I kill the connection to the server in order to test the new functionality, the buttons I use don't go back to their "not-pressed" state. Is this something that this PR should consider?

image

**Comment by AngieDutra** [comment]
> Nice job! I left a few minor comments about the code.
> 
> Also, I noticed that when I kill the connection to the server in order to test the new functionality, the buttons I use don't go back to their "not-pressed" state. Is this something that this PR should consider?
> 
> image

This happens due to the button selection script. I think it is not detecting a pointer up when the pop up is activated, so it stays with pressed styles until refresh. But I should look into all buttons and how they are working because I've found several issues regarding this. Also, what I change in this script will affect all buttons so I would do it in another PR. You could do an issue for this tho

File: client/Assets/Scripts/LobbyConnection.cs (hunk 1 above)
Comment (AminArria) [reply client/Assets/Scripts/LobbyConnection.cs]: Removed

File: client/Assets/Scripts/LobbyConnection.cs (hunk 3 above)
Comment (AminArria) [reply client/Assets/Scripts/LobbyConnection.cs]: Renamed

File: client/Assets/Scripts/SocketConnectionManager.cs (hunk 2 above)
Comment (AminArria) [reply client/Assets/Scripts/SocketConnectionManager.cs:209]: Renamed

**Comment by BertovDev** [comment]
> Nice work @AminArria and @BertovDev! I enjoyed working together

Same for me!!!

**Review by BertovDev — APPROVED** [review]
Awesome!! 🤩
