### PR TITLE
Dynamic position for basic skill

### LINKED ISSUE #1072: [FEATURE] Dynamic basic skill position
## 🚀 Feature
Allow players to tap anywhere on the right side of the screen to trigger the basic skill (temporarily move the basic button to that position until release), similar to the implementation of the movement button. The exception, of course, is the other buttons.

### PR DESCRIPTION
**Pull request by AngieDutra**
This PR closes #1072 
This PR changes the basic skill input positioning. To test it the reviewer should be able to use the basic skill pressing anywhere from the middle to the right side of the screen. The only exceptions of use are when pressing the other two inputs (skill1 and crate).
Also check:
- Responsive max range in joystick 
- When pressing the right side of the screen the input should always stay within the screen view
- Our new cancel option. If you press hack's skill without aiming it should fire in the current direction of the player. If you were to want to cancel the skill after dragging it, you should drag the joystick's knob back to the center from which you dragged it from.

### CODE REVIEW

**Comment by BertovDev** [comment]
increase cancel Area of the button. Now its so difficult to hit the cancel.

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs [hunk 1]
```diff
@@ -49,4 +75,16 @@ public void UnSetJoystick()
         Image joystickBg = gameObject.transform.parent.gameObject.GetComponent<Image>();
         joystickBg.enabled = false;
     }
+
+    public void CancelAttack(Vector2 value, bool dragged)
+    {
+        if (value.x < 0.5f && value.x > -0.5f && value.y < 0.5f && value.y > -0.5f)
```
Comment (saugon) [inline client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:81]: The value 0.5f should be declared as a constant to enhance maintenance and readability, as well as to avoid the use of magic numbers.

File: client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+        base.Start();
+        scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;
+        _initialPosition = BackgroundCanvasGroup.transform.position;
+    }
+
+    public override void OnPointerDown(PointerEventData eventData)
+    {
+        base.OnPointerDown(eventData);
+        ClampJoystickPositionToScreen(eventData);
+        if (KnobCanvasGroup.GetComponent<CustomMMTouchJoystick>().isActiveAndEnabled)
```
Comment (saugon) [inline client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs:22]: There are many calls to GetComponent in this script that could potentially be enhanced, perhaps by utilizing an attribute that can be set in the Start method.

Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs]: Both comments were fixed!

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs (hunk 1 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchJoystick.cs]: Done!

File: client/mono_crash.mem.4740.1.blob
Comment (BertovDev) [inline client/mono_crash.mem.4740.1.blob:1]: Delete This

**Review by BertovDev — CHANGES_REQUESTED** [review]
Loading GO in CameraUI prefab is inactive.

**Review by tkz00 — CHANGES_REQUESTED** [review]
The variable previousDrag in CustomMMTouchJoystick is unused and should be deleted. Also in this script the variable scaleCanvas is only used inside the RefreshMaxRangeDistance method so it should be a method-local variable and contained only within that scope, not the classes one.

**Comment by AngieDutra** [comment]
> scaleCanvas

In some cases this was useful. Also helped me notice one scaleCanvas wasn't being applied when it should have

File: client/mono_crash.mem.4740.1.blob
Comment (AngieDutra) [reply client/mono_crash.mem.4740.1.blob:1]: I did! Both things were fixed, thanks

**Review by tkz00 — DISMISSED** [review]
Looks great! Nice work!

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs [hunk 3]
```diff
@@ -10,6 +10,15 @@ public class CustomMMTouchJoystick : MMTouchJoystick
     public UnityEvent<Vector2, CustomMMTouchJoystick> newDragEvent;
     public UnityEvent<CustomMMTouchJoystick> newPointerDownEvent;
     public Skill skill;
+    const float cancelAreaValue = 0.5f;
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:13]: We should follow the standar for Constants. This should be `CANCEL_AREA_VALUE`

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs [hunk 4]
```diff
@@ -49,4 +74,21 @@ public void UnSetJoystick()
         Image joystickBg = gameObject.transform.parent.gameObject.GetComponent<Image>();
         joystickBg.enabled = false;
     }
+
+    public void CancelAttack(Vector2 value, bool dragged)
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:78]: You dont need this parameters since their are field of the class. You can access `RawValue` and `dragged` without passing it by parameter.

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs [hunk 5]
```diff
@@ -22,16 +31,32 @@ public override void OnPointerDown(PointerEventData data)
...
+        dragged = true;
+        CancelAttack(RawValue, dragged);
         newDragEvent.Invoke(RawValue, this);
     }
 
     public override void OnPointerUp(PointerEventData data)
     {
         newPointerUpEvent.Invoke(RawValue, skill);
+        dragged = false;
+        CancelAttack(RawValue, dragged);
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:43]: Remove this parameters

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs [hunk 6]
```diff
@@ -22,16 +31,32 @@ public override void OnPointerDown(PointerEventData data)
     public override void OnDrag(PointerEventData eventData)
     {
         base.OnDrag(eventData);
+        dragged = true;
+        CancelAttack(RawValue, dragged);
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:35]: Remove this parameters

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs [hunk 7]
```diff
@@ -22,16 +31,32 @@ public override void OnPointerDown(PointerEventData data)
...
+        dragged = false;
+        CancelAttack(RawValue, dragged);
         UnSetJoystick();
         ResetJoystick();
     }
 
+    public override void RefreshMaxRangeDistance()
+    {
+        // What makes this responsive is taking into account the canvas scaling
+        float scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:51]: `float scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;`

.gameObject is not necessary here you can simply do: 
`GetComponentInParent<Canvas>().transform.localScale.x;`

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs [hunk 8]
```diff
@@ -22,16 +31,32 @@ public override void OnPointerDown(PointerEventData data)
...
+
+        float knobBackgroundRadius =
+            gameObject.transform.parent.GetComponent<RectTransform>().rect.width / 2;
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:54]: Same here `.gameObject` not necessary.

File: client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs [hunk 9]
```diff
@@ -0,0 +1,83 @@
...
+    float positionX;
+    float positionY;
+    float scaleCanvas;
+    CustomMMTouchJoystick knobJoystick;
+    CustomMMTouchButton knobButton;
+
+    protected override void Start()
+    {
+        base.Start();
+        scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;
```
Comment (BertovDev) [inline client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs:16]: This Scripts looks awesome just delet unecessary `.gameObject`.

`GetComponentInParent<Canvas>().gameObject.transform.localScale.x;`
 to
`GetComponentInParent<Canvas>().transform.localScale.x;`

**Review by BertovDev — DISMISSED** [review]
This is working so clean, congrats! just minor code changes/improvements that i believe that might be fine

File: client/Assets/Scripts/CustomInputManager.cs [hunk 10]
```diff
@@ -407,12 +412,13 @@ public void HideSkillRange()
...
             .GetComponent<CustomCharacter>()
-            .characterBase.SkillRange.transform;
-        Color32 newColor = cancelable ? new Color32(255, 0, 0, 255) : characterSkillColor;
-        material = skillRange.GetComponentInChildren<MeshRenderer>().material;
-        material.SetColor("_Color", newColor);
+            .characterBase.SkillRange.GetComponentInChildren<MeshRenderer>()
+            .material;
+        skillRangeMaterial.SetColor("_Color", characterSkillColor);
+
+        _player.GetComponentInChildren<AimDirection>().DeactivateIndicator();
```
[the remark this answers is not in the document]
Comment (AngieDutra) [reply client/Assets/Scripts/CustomInputManager.cs:421]: I used directionIndicator to tackle this. The rest I believe a refactor is needed since I can access AimDirection in more than one way

File: client/Assets/Scripts/CustomInputManager.cs [hunk 11]
```diff
@@ -439,9 +445,12 @@ public void SetCanceled(bool value)
         canceled = value;
         if (directionIndicator)
         {
-            directionIndicator.CancelableFeedback(value);
+            directionIndicator.DeactivateIndicator();
+        }
+        if (_player)
+        {
+            SetSkillRangeCancelable(value);
```
[the remark this answers is not in the document]
Comment (AngieDutra) [reply client/Assets/Scripts/CustomInputManager.cs:452]: done!

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs (hunk 3 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:13]: Agree! changed it

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs (hunk 5 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:43]: done

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs (hunk 6 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:35]: done

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs (hunk 7 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:51]: cool, done

File: client/Assets/Scripts/UI/CustomMMTouchJoystick.cs (hunk 8 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchJoystick.cs:54]: done

File: client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs (hunk 9 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs:16]: done

**Review by tkz00 — APPROVED** [review]
Looks great!

**Review by ncontinanza — APPROVED** [review]
LGTM!
