### PR TITLE
Fix bot bugs

### LINKED ISSUE #823: [BUG] Fix Bot Bugs
Captura de pantalla 2023-08-25 a la(s) 15 27 21

### PR DESCRIPTION
**Pull request by ncontinanza**
Closes #823 

Both of the reported errors were happening due to a very brief difference between the number of players in the server and the one in the client. The GameEvent received by the client did not have as many players as the `gamePlayers` list in the SocketConnectionManager.

### CODE REVIEW

File: client/Assets/Scripts/Battle.cs [hunk 1]
```diff
@@ -204,87 +204,91 @@ void UpdatePlayerActions()
...
 
-            // This call to `new` here is extremely important for client prediction. If we don't make a copy,
-            // prediction will modify the player in place, which is not what we want.
-            Player serverPlayerUpdate = new Player(gameEvent.Players[i]);
-
-            if (
-                serverPlayerUpdate.Id == (ulong)SocketConnectionManager.Instance.playerId
-                && useClientPrediction
-            )
+            // There are a few frames during which this is outdated and produces an error
```
Comment (mgrunwaldt) [inline client/Assets/Scripts/Battle.cs:207]: I don't understand this comment, does it still produce an error? what kind of error?

Comment (ncontinanza) [reply client/Assets/Scripts/Battle.cs:207]: It raises a NullReferenceException, because there's a difference between those two lists in the server. That new conditional prevents that situation, not performing the update for those few frames.

**Review by mgrunwaldt — APPROVED** [review]

**Review by BertovDev — APPROVED** [review]
